language: java
jdk:
  - openjdk8

branches:
  only:
    - seungmin

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


before_deploy:
  - zip -r springBootBlog *
  - mkdir -p deploy
  - mv springBootBlog.zip deploy/springBootBlog.zip

deploy:
  -provider : s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  bucket: seungmin-springboot-blog
  region: ap-northeast-2
  skip_cleanup: true›
  acl: private
  local_dir: deploy
  wait-until-deployed : true
  on:
    all_branches: true

  -provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: seungmin-springboot-blog
  key: springBootBlog.zip
  bundle_type: zip
  application: spring-boot-blog
  deployment_group: spring-boot-blog-group
  region: ap-northeast-2
  wait-until-deployed : true
  on:
    all_branches: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      -tmd9544@gmail.com


